// <auto-generated />
using Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountDbContext))]
    partial class DiscountDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 250,
                            Description = "MacBook Special Discount",
                            ProductName = "MacBook Pro M2"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 80,
                            Description = "Headphones Limited Offer",
                            ProductName = "Sony WH-1000XM5"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 200,
                            Description = "Laptop Seasonal Discount",
                            ProductName = "Dell XPS 13"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 120,
                            Description = "Tablet Promo Discount",
                            ProductName = "iPad Air"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
